project:
  type: book

book:
  title: "Neural Networks...from Sratch!"
  author: "Norah Jones"
  date: "3/5/2026"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



